# name of the environment and k8s namespace
# leave 'namespace' value blank to use value from 'env' parameter
env: "development"
namespace:

envVariables:
- name: NODE_ENV
  value: "development"
replicas:
  min: 1
  max: 2
  cpu: 90
  memory: 70

ingresses:
- name: restricted
  domain: "orca-hello"
  class: "nginx-public"
  annotations:
  - key: nginx.ingress.kubernetes.io/whitelist-source-range
    value: "114.42.48.190" # SG office IP


imagePullPolicy: Always
