# name of the environment and k8s namespace
# leave 'namespace' value blank to use value from 'env' parameter
env: "stagin"
namespace:

envVariables:
- name: NODE_ENV
  value: "stagin"
replicas:
  min: 1
  max: 2
  cpu: 90
  memory: 70

ingresses: